services:
  - type: web            # ← changed from "worker"
    name: starknet-buybot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_TOKEN
